/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;
import com.raven.model.ModelUser;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author Lenovo
 */
public class Form_Home extends javax.swing.JPanel {
    
        private final ModelUser user;

    /**
     * Creates new form Form_Home
     */
    public Form_Home(ModelUser user) {
        this.user = user;
        initComponents();
        lbUser.setText(user.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ImageIcon originalIcon = new ImageIcon("C:\\Users\\Lenovo\\Downloads\\pngegg.png");
        Image originalImage = originalIcon.getImage();
        BufferedImage bufferedImage = new BufferedImage(
            originalImage.getWidth(null),
            originalImage.getHeight(null),
            BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = bufferedImage.createGraphics();
        g2d.drawImage(originalImage, 0, 0, null);
        g2d.dispose();
        for (int y = 0; y < bufferedImage.getHeight(); y++) {
            for (int x = 0; x < bufferedImage.getWidth(); x++) {
                int argb = bufferedImage.getRGB(x, y);
                int alpha = (argb >> 24) & 0xFF;
                int newAlpha = (int) (alpha * 0.75); // Adjust transparency level here
                argb = (argb & 0x00FFFFFF) | (newAlpha << 24);
                bufferedImage.setRGB(x, y, argb);
            }
        }
        ImageIcon transparentIcon = new ImageIcon(bufferedImage);
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1060, 730));
        setPreferredSize(new java.awt.Dimension(1060, 730));
        setLayout(null);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome to e-swasthya.");
        add(jLabel3);
        jLabel3.setBounds(10, 230, 1030, 60);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel6.setText("Click on any button given in the \"My Feed\" Section");
        add(jLabel6);
        jLabel6.setBounds(80, 310, 920, 80);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel4.setText("given in the left panel of this page");
        add(jLabel4);
        jLabel4.setBounds(230, 340, 920, 110);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel5.setText("To continue your healthy journey with us,");
        add(jLabel5);
        jLabel5.setBounds(180, 240, 810, 130);

        lbUser.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        add(lbUser);
        lbUser.setBounds(480, 120, 480, 63);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel1.setText("Hello,");
        add(jLabel1);
        jLabel1.setBounds(340, 120, 150, 60);

        jLabel2.setIcon(transparentIcon);
        jLabel2.setFocusable(false);
        add(jLabel2);
        jLabel2.setBounds(80, 0, 1060, 730);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbUser;
    // End of variables declaration//GEN-END:variables
}
