/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.swing;

import com.raven.model.Model_Menu;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;

/**
 *
 * @author Lenovo
 */
public class MenuItem extends javax.swing.JPanel {

    /**
     * Creates new form MenuItem
     */
    private boolean selected;
    private boolean over;
    
    public MenuItem(Model_Menu data) {
        initComponents();
        setOpaque(false);
        if(data.getType()==Model_Menu.MenuType.MENU)
        {

            lbName.setText(data.getName());
              lbName.setFont(new Font("sansserif",2,24));
              // Center the text horizontally and vertically
//            lbName.setHorizontalAlignment(JLabel.CENTER);
//            lbName.setVerticalAlignment(JLabel.CENTER);
              
        } else if (data.getType()==Model_Menu.MenuType.TITLE){
             lbName.setText(data.getName());
             lbName.setFont(new Font("sansserif",Font.BOLD,28));
             lbName.setVisible(true);
        }else {
            lbName.setText(" ");
        }
    }

     public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }
     
     public void setOver(boolean over){
         this.over = over;
         repaint();
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();

        lbName.setForeground(new java.awt.Color(255, 255, 255));
        lbName.setText("Menu Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
    protected void paintComponent(Graphics grphcs){
        if(selected || over){
            Graphics2D g2=(Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
       if(selected){
            g2.setColor(new Color(255,255,255,80));
       }else{
           g2.setColor(new Color(255,255,255,20));
       }
        g2.fillRoundRect(0,0,getWidth(),getHeight(),5,5);
         FontMetrics fontMetrics = g2.getFontMetrics(lbName.getFont());
        int textX = (getWidth() - fontMetrics.stringWidth(lbName.getText())) / 2;
        int textY = (getHeight() - fontMetrics.getHeight()) / 2 + fontMetrics.getAscent();
        lbName.setBounds(textX, textY, fontMetrics.stringWidth(lbName.getText()), fontMetrics.getHeight());
        lbName.paint(g2);

        }
        super.paintComponent(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbName;
    // End of variables declaration//GEN-END:variables

    /**
     * @param selected the selected to set
     */
   
}
