/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.component;

import com.raven.event.EventMenuSelected;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;

import javax.swing.JFrame;

import com.raven.model.Model_Menu;

/**
 *
 * @author Lenovo
 */
public class menu extends javax.swing.JPanel {
    private EventMenuSelected event;
    /**
     * Creates new form menu
     */
    public void addEventMenuSelected(EventMenuSelected event){
        this.event = event;
        listMenu1.addEventMenuSelected(event);
    }
    public menu() {
        initComponents();
        setOpaque(false);
        listMenu1.setOpaque(false);
        init();
    }   
    private void  init(){
        listMenu1.addItem(new Model_Menu( "            My Feed", Model_Menu.MenuType.TITLE));
        listMenu1.addItem(new Model_Menu( "   Video Feed", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu( "   Check my Calories", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu( "   Recipes for you", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu( "   Fitness Centre", Model_Menu.MenuType.MENU)); //exercizes
        listMenu1.addItem(new Model_Menu( "", Model_Menu.MenuType.EMPTY)); 
        
        listMenu1.addItem(new Model_Menu( "          My account", Model_Menu.MenuType.TITLE));
        listMenu1.addItem(new Model_Menu( "    Account Centre", Model_Menu.MenuType.MENU));

        

                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmoving = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listMenu1 = new com.raven.swing.ListMenu();

        setOpaque(false);

        panelmoving.setOpaque(false);

        javax.swing.GroupLayout panelmovingLayout = new javax.swing.GroupLayout(panelmoving);
        panelmoving.setLayout(panelmovingLayout);
        panelmovingLayout.setHorizontalGroup(
            panelmovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );
        panelmovingLayout.setVerticalGroup(
            panelmovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("e-swasthya ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelmoving, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(77, 77, 77))
            .addComponent(listMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelmoving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(listMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
       protected void paintChildren(Graphics grphcs){
              Graphics2D g2=(Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//        g2.setColor(getBackground());
        GradientPaint g=new GradientPaint(0, 0, new Color(29,147,117), 0, getHeight(), new Color(22, 116, 66));
        g2.setPaint(g);
        g2.fillRect(getWidth()-20,0,getWidth(),getHeight());
        g2.fillRoundRect(0,0,getWidth(), getHeight(), 0,0);
           super.paintChildren(grphcs);
       }
       
       private int x;
       private int y;
       public void initMoving(JFrame fram){
           panelmoving.addMouseListener(new MouseAdapter()
           {
               @Override
               public void mousePressed(MouseEvent me){
                   x = me.getX();
                   y = me.getY();
               }
           });
           panelmoving.addMouseMotionListener(new MouseMotionAdapter()
           {
               @Override
               public void mouseDragged(MouseEvent me){
                   fram.setLocation (me.getXOnScreen() - x, me.getYOnScreen() -y );
                   super.mouseDragged(me);
               }
           });
       }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.raven.swing.ListMenu listMenu1;
    private javax.swing.JPanel panelmoving;
    // End of variables declaration//GEN-END:variables
}


//database resetup: youtube feed + symptoms checker ki jagah kuch aur karo bhai